config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get '/', to: 'pages#home'
  get '/home', to: 'pages#home'
  get '/projects', to: 'pages#projects'
  get '/contact', to: 'pages#contact'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def projects
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MiPortafolio</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
<nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container">
        <a class="navbar-brand" href="/">Inicio</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <%= link_to "Proyectos", projects_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Contacto", contact_path, class: "nav-link" %>
            </li>
          </ul>
        </div>
      </div>
    </nav>  
  </head>

  <body>
    <%= yield %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.5.3/dist/js/bootstrap.min.js"></script>

  </body>
</html>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/home.html.erb
<div class="row">
<div class="container-center">

<div class="spinner-border text-primary" role="status">
  <span class="visually-hidden">Loading...</span>
</div>
<div class="spinner-border text-secondary" role="status">
  <span class="visually-hidden">Loading...</span>
</div>
<div class="spinner-border text-success" role="status">
  <span class="visually-hidden">Loading...</span>
</div>
<div class="spinner-border text-danger" role="status">
  <span class="visually-hidden">Loading...</span>
</div>
<div class="spinner-border text-warning" role="status">
  <span class="visually-hidden">Loading...</span>
</div>
<div class="spinner-border text-info" role="status">
  <span class="visually-hidden">Loading...</span>
</div>
<div class="spinner-border text-light" role="status">
  <span class="visually-hidden">Loading...</span>
</div>
<div class="spinner-border text-dark" role="status">
  <span class="visually-hidden">Loading...</span>
</div>
</div>
</div>

app/views/pages/projects.html.erb
<div class="container">

<div class="row">
  <div class="col-md-4">
    <div class="card">
      <div class="card-body">
        <%= image_tag 'iguana-2.jpg', width: 300, height: 200  %>

        <h5 class="card-title">Proyecto 1</h5>
        <p class="card-text">Descripción del proyecto 1.</p>

        <a href="" class="btn btn-primary">Ver más</a>
      </div>
    </div>
  </div>

  <div class="col-md-4">
    <div class="card">

      <div class="card-body">
        <%= image_tag 'iguana-3.jpg', width: 300, height: 200 %>

        <h5 class="card-title">Proyecto 2</h5>
        <p class="card-text">Descripción del proyecto 2.</p>

        <a href="#" class="btn btn-primary">Ver más</a>
      </div>
    </div>
  </div>

  <div class="col-md-4">
    <div class="card">
      <div class="card-body">
        <%= image_tag 'iguana-4.jpg' , width: 300, height: 200 %>

        <h5 class="card-title">Proyecto 3</h5>
        <p class="card-text">Descripción del proyecto 3.</p>

        <a href="#" class="btn btn-primary">Ver más</a>
      </div>
    </div>
  </div>
</div>
    </div>